### ISSUE TITLE
rabbitmq_plugins circular dependency

### ISSUE THREAD

**Issue by nmistry** [saltstack-formulas/rabbitmq-formula#20] opened 2015-07-28 07:14 UTC
On the initial run of this formua, if the `rabbitmq` pillar contains any plugins the whole formula wont execute.   The `rabbitmq` or `rabbitmq.latest` wont execute because `rabbitmq_plugin` fails. 

```
# salt-call state.single rabbitmq_plugin.enabled rabbitmq_management
```

returns: 

```
local:
    Data failed to compile:
----------
    Specified state 'rabbitmq_plugin.enabled' was not found
```

The root cause is the requirement of `rabbitmqctl` by salt's  bundled rabbitmq_plugin.py state.   Details are here:
https://github.com/saltstack/salt/blob/develop/salt/states/rabbitmq_plugin.py#L23-L29

**Comment by gravyboat** [comment] 2015-07-28 17:47
Did you create an issue for this on the main salt repo?

**Comment by nmistry** [comment] 2015-07-29 03:21
@gravyboat, posted here first to see if it was something obvious that I missed and to make sure it was captured.

**Comment by gravyboat** [comment] 2015-07-29 05:54
@nmistry Gotcha, I'm not aware of this issue, nor have I seen mention of it. It might be an edge case issue. I also checked the main salt repo for issues and I don't see anything over there. Could you pull some details together regarding salt version and so forth and create an issue there? It seems like an issue with how salt is doing the library loading after rabbitmq gets installed is problematic. Linking that same section of lines would be good as well.

**Comment by nmistry** [comment] 2015-07-29 08:45
Tomorrow I will put together a gist with an example configuration and the error details and cross post w/ a salt issue.

**Comment by dicato** [comment] 2015-07-31 15:32
I ran into this same issue today and am happy to help fix and test. It's unclear to me exactly what the root cause is.

My current workaround is to ssh to the minion and manually install `rabbitmq-server`.

**Comment by vr-jack** [comment] 2015-08-13 22:19
The issue is rabbitmq_plugins state cannot load until the package is installed.
https://github.com/saltstack/salt/blob/develop/salt/states/rabbitmq_plugin.py#L27

You cannot include the config in the same file you have the package install. You can do:

include:
  rabbitmq.install
  rabbitmq.config

And then move all the init.sls stuff into rabbitmq.install

We tested this by moving it to the include list in rabbitmq.latest for a case where .latest was being run and it passed through okay.

FYI: there are dependencies in mysql modules too. See how they did their init.sls in the mysql-formula.

**Comment by PredatorVI** [comment] 2015-08-13 22:53
vr-jack helped me diagnose and get past this.  Happy to help test any permanent solutions.  For now, in my 'fork' I put the rabbitmq.config include into the latest.sls file.

**Comment by puneetk** [comment] 2015-08-13 23:09
Send a pull request with the change where u add the rabbitmq.config to the include in the latest.sls file and we can merge it in.

**Comment by gravyboat** [comment] 2015-08-14 06:15
Closing since https://github.com/saltstack-formulas/rabbitmq-formula/pull/27 is merged.

**Closed by gravyboat** 2015-08-14 06:15 UTC
